import { PmPagedLinks } from "./PmPagedCollection";
import { UserRight } from "./UserRight";

export interface User {
  userId: number;
  loginId: string;
  email: string;
  firstName?: string;
  lastName: string;
  company?: string;
  userType: number;
  currencyCode: number;
  laborRateCurrencyCode: number;
  languageId: number;
  localeId: number;
  autoSave: number;
  dateFormat: number;
  timeFormat: number;
  numberFormatId: number;
  timezoneId: number;
  paperSize: number;
  themeId?: number;
  htmlEmail: boolean;
  notificationTypeId?: number;
  analyzeAllDomains: number;
  isPinReset: number;
  passwordExpires: number;
  passwordSetDate?: string;
  adHocUser: boolean;
  activeFlag: number;
  applicationUser: boolean;
  portalUser: boolean;
  reviewUser: boolean;
  isOutOfOffice: boolean;
  outOfOfficeStatus?: number;
  lastLoginDate?: string;
  clientLoggingLevel: number;
  preferredLandingPage?: number;
  spendFocusedView?: number;
  groups: number[];
  rights: UserRight[];
  inheritedRights?: UserRight[];
  investmentReviewUserBackups: { userId: number }[];
  investmentReviewGroupBackups: { groupId: number }[];
  activityFinancialUserBackups: { userId: number }[];
  activityFinancialGroupBackups: { groupId: number }[];
  conceptReviewUserBackups: { userId: number }[];
  conceptReviewGroupBackups: { groupId: number }[];
  workflowUserBackups: { userId: number }[];
  workflowGroupBackups: number[];
  adamLoginId?: string;
  adamUserId?: string;
  extendedAttributes?: unknown[];
  multipleValueExtendedAttributes?: unknown[];
  _links?: PmPagedLinks;
}
