import { ApiLink } from "./ApiLink";
import { DownloadLinkTargetCollection } from "./DownloadLinkTargetCollection";
import { MaintenanceJobStatus } from "./MaintenanceJob";
import { User } from "./User";

/**
 * Storage class for download links in ADAM. Download links are outputs from maintenance jobs and
 * orders (DownloadOrder, ExportMaintenanceJob, ContactSheet, ExportAuditJob).
 */
export interface DownloadLink {
  /** Gets the creation datetime in UTC time. Format: date-time. */
  createdOn: string;
  /** List of download links to the files generated by the order or maintenance job. */
  deliveredFiles: string[];
  /** Gets the description of a download link. */
  description: string;
  /** Ids of download agreements, if any applicable to any record in download. */
  downloadAgreementIds: number[];
  /** Get the user friendly error description from download link. */
  errorDescription: string;
  /** Gets the count of records for which there were errors when processing of any requested files. Format: int32. */
  failedRecordsCount: number;
  /** Gets the count of failed targets. Format: int32. */
  failedTargetsCount: number;
  /** Gets the Id of this maintenance job. */
  id: string;
  /**
   * Gets the status of this download link.
   */
  status: MaintenanceJobStatus;
  /** Gets the count of records for which all requested files were successfully processed. Format: int32. */
  succeededRecordsCount: number;
  /** Gets the title of a download link. */
  title: string;
  /** Gets the type of download link. */
  type: string;
  _links: DownloadLinkLinks;
  _embedded?: {
    [K in Exclude<
      keyof DownloadLinkLinks,
      "self"
    >]?: DownloadLinkLinks[K] extends ApiLink<infer R> ? R : never;
  };
}

export interface DownloadLinkLinks {
  self: ApiLink;
  targets: ApiLink<DownloadLinkTargetCollection>;
  createdby: ApiLink<User>;
}
