import { AdditionalFileCollection } from "./AdditionalFileCollection";
import { ApiLink } from "./ApiLink";
import { FilePreview } from "./FilePreview";
import { FilePreviewCollection } from "./FilePreviewCollection";
import { FileType } from "./FileType";
import { FileVersionAnnotationInfo } from "./FileVersionAnnotationInfo";
import { FileVersionDuplicateInfo } from "./FileVersionDuplicateInfo";
import { FileVersionMetadata } from "./FileVersionMetadata";
import { FileVersionPermissions } from "./FileVersionPermissions";
import { Image } from "./Image";
import { LinkedVersionInfoCollection } from "./LinkedVersionInfoCollection";
import { PublicLinkCollection } from "./PublicLinkCollection";
import { PublicUriCollection } from "./PublicUriCollection";
import { RenditionCollection } from "./RenditionCollection";
import { User } from "./User";
import { Watermark } from "./Watermark";

/**
 * Representation of a specific version of a file attached to a record.
 *
 * Pass an {@link Expander} chain `for<FileVersion>("FileVersion")` to populate
 * related resources under `_embedded`. Expandable keys: `filetype`,
 * `filepreviews`, `masterfilepreview`, `preview`, `thumbnail`, `additionalfiles`,
 * `renditions`, `publiclinks`, `watermark`, `publicuris`, `permissions`,
 * `usedin`, `contains`, `createdby`.
 */
export interface FileVersion {
  /**
   * Indicates if this file version has content generated by AI.
   */
  aiInfluenced: "Unknown" | "No" | "Yes";
  /** Annotation information for this file version. */
  annotationInfo: FileVersionAnnotationInfo | null;
  /** A comment or note about this file version. */
  comment: string;
  /** Custom XML content associated with this file version. */
  content: string | null;
  /** CRC32 checksum of this file version. Format: int32. */
  crc32: number;
  /** The datetime when this version was created, in UTC time. */
  createdOn: string;
  /** Information about potential duplicates of this file version. */
  duplicateInfo: FileVersionDuplicateInfo | null;
  /** The original creation datetime of the physical file. */
  fileCreatedOn: string;
  /** The file extension (without the dot). */
  fileExtension: string;
  /** The datetime when the physical file was last modified, in UTC time. */
  fileModifiedOn: string;
  /** The filename including extension. */
  fileName: string;
  /** Processing state of this file version. */
  fileProcessingState: string;
  /** The file size in bytes. Format: int64. */
  fileSize: number;
  /**
   * The current state of the file.
   */
  fileState: "Available" | "Processing";
  /** Indicates if there are smart action scan findings for this file version. */
  hasSmartActionFindings: boolean | null;
  /** The unique identifier (GUID) of this file version. AprimoId. */
  id: string;
  /** Indicates if this is the latest version of the file. */
  isLatest: boolean;
  /** Extracted technical metadata from the file (EXIF, XMP, etc.). */
  metadata: { [key: string]: FileVersionMetadata } | null;
  /** Indicates whether downloading this file version is prevented by policy. */
  preventDownload: boolean;
  /** Items (pages, chapters) included in this publication, for publication files. */
  publicationItems: object[] | null;
  /** IDs of publications that include this file version as an item. */
  publications: string[] | null;
  /** SHA-256 hash of this file version. */
  sha256: string | null;
  /** Custom XML tag data for this file version. */
  tag: string | null;
  /** A human-readable label for this version. */
  versionLabel: string;
  /** The sequential version number. Format: int32. */
  versionNumber: number;
  /** The ID of the watermark configuration applied to this version. AprimoId. */
  watermarkId: string;
  /**
   * How watermarking is configured for this file version.
   */
  watermarkType: "None" | "InheritFromFile" | "UseSpecified" | "UseSetting";
  _links: FileVersionLinks;
  _embedded?: {
    [K in Exclude<
      keyof FileVersionLinks,
      "self"
    >]?: FileVersionLinks[K] extends ApiLink<infer R> ? R : never;
  };
}

/**
 * HAL link relations for a {@link FileVersion}.
 */
export interface FileVersionLinks {
  /** Self link. */
  self: ApiLink;
  /** The file type definition for this file. */
  filetype: ApiLink<FileType>;
  /** Collection of preview files generated for this version. */
  filepreviews: ApiLink<FilePreviewCollection>;
  /** The master preview for this version. */
  masterfilepreview: ApiLink<FilePreview>;
  /** Preview image of this version. */
  preview: ApiLink<Image>;
  /** Thumbnail image of this version. */
  thumbnail: ApiLink<Image>;
  /** Additional files associated with this version. */
  additionalfiles: ApiLink<AdditionalFileCollection>;
  /** Renditions generated for this version. */
  renditions: ApiLink<RenditionCollection>;
  /** Public CDN links for this version. */
  publiclinks: ApiLink<PublicLinkCollection>;
  /** Watermark configuration. */
  watermark: ApiLink<Watermark>;
  /** Public URI links. */
  publicuris: ApiLink<PublicUriCollection>;
  /** User permissions on this file version. */
  permissions: ApiLink<FileVersionPermissions>;
  /** Linked file versions that use this version. */
  usedin: ApiLink<LinkedVersionInfoCollection>;
  /** Linked file versions contained by this version. */
  contains: ApiLink<LinkedVersionInfoCollection>;
  /** User who created this version. */
  createdby: ApiLink<User>;
}
